version: "3.2"
services:
  php1:
    build: './php/'
    volumes:
      - ./src/:/var/www/html/
  php2:
    build: './php/'
    volumes:
      - ./src/:/var/www/html/
  web:
    build: './nginx/'
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
volumes:
  persistent: