version: "3.2"
services:
  php:
    build: './php/'
    volumes:
      - ./src/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: "@dm1n"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
volumes:
  persistent: